# **Module Numpy (Numerical Python)**
Module dari luar python dan harus diinstall terlebih dahulu pip install numpy. Module ini berfokus pada scientific computing dan biasanya digunakan untuk perhitungan scientific seperti matrix, aljabar, statistic, dan sebagainya.

link documentation numpy : https://numpy.org/doc/stable/

<hr></hr>

## **Sedikit Pendahuluan**
### Array vs List
Meskipun memiliki bentuk matrix yang mirip dengan 'list' bawaan dari python, array dalam numpy bekerja dengan cara yang sedikit berbeda.

In [5]:
import numpy as np
array = np.array([1,2,3,4,5])
lists = [1,2,3,4,5]

print(f"Array = {array}")
print(f"List = {lists}")

print("----------------------------")

array += 1
lists += [1]
print("Ketika ditambah satu array akan menjumlah setiap value isinya, \nsementara list menambahkan anggota (ini karena list tidak dapat hanya + 1 begitu saja)")
print(f"Array = {array}")
print(f"List = {lists}")



Array = [1 2 3 4 5]
List = [1, 2, 3, 4, 5]
----------------------------
Ketika ditambah satu array akan menjumlah setiap value isinya, 
sementara list menambahkan anggota (ini karena list tidak dapat hanya + 1 begitu saja)
Array = [2 3 4 5 6]
List = [1, 2, 3, 4, 5, 1]


<hr></hr>

## **Initialize Array**
### Berdasarkan Ukuran
#### Array Satu Dimensi
Pembuatan array dapat secara manual (a), list, maupun tuple seperti dibawah ini. If you look it more clearly there is slight difference between numpy array dan array java / c++ yaitu array numpy dapat terdiri dari anggota yang tidak homogen.

In [16]:
import numpy as np

inilist = [1,2,3,"a",5]
inituple = [1,2,3,False,5]

a = np.array([1,2,3,4,5], dtype = float) #dtype dapat ditulis maupun tidak
b = np.array(inilist)
c = np.array(inituple)

print (a) # array biasa
print (b) # array dari list
print (c) # array dari tuple

print(20*"=")

withrange = np.arange(1,5,0.5)
print(withrange)

withlinspace = np.linspace(1,5,3)
print(withlinspace)

[1 2 3 4 5]
['1' '2' '3' 'a' '5']
[1 2 3 0 5]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[1. 3. 5.]


#### Array Multi Dimension

In [30]:
twod = np.array([ (1,2,3) , (4,5,6) ])
print(twod)

[[1 2 3]
 [4 5 6]]


### Berdasarkan Isi Arraynya
#### Array dengan semua nilainya 0

In [29]:
# martix dengan nilai nol
zerod = np.zeros(5)
zerotwod = np.zeros((3,3))
print(zero)
print(zerotwod)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Array dengan semua nilainya 1

In [31]:
# martix dengan nilai satu
oned = np.ones(5)
onetwod = np.ones((3,3))
print(oned)
print(onetwod)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Array dengan semua nilainya kita tentukan

In [6]:
# matrix full
p3 = np.full((2,3),6)
p4 = np.full((5),9)
print(p3)
print(p4)

[[6 6 6]
 [6 6 6]]
[9 9 9 9 9]


#### Array Identitas

In [35]:
# martix identitas
p = np.identity(4)
print(p)

p2 = np.eye(4)
print(p2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Based on how they made
#### Using Function
We can use `np.fromfunction(funcname, size, type)`
This function will construct an array by executing a funcname over each coordinate.
funcname yang didalam dipanggil dengan N parameter yang mana N adalah jumlah shapenya.

In [5]:
import numpy as np
def kuadrat(baris,kolom):
    return kolom**3

b = np.fromfunction(kuadrat,(1,10), dtype=int)
print(b)


[[  0   1   8  27  64 125 216 343 512 729]]


In [14]:
def jumlah(baris,kolom):
    return kolom+baris

c = np.fromfunction(jumlah,(4,4), dtype=float)
print(c)

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


#### Using Iterable
We can use `np.fromiter(itername, type)`

In [8]:
イテラブル = (x*x for x in range(5))
g = np.fromiter(イテラブル, dtype=int)
print(g)

[ 0  1  4  9 16]


#### Using Random
np.floor digunakan untuk membulatkan angka, dan random.rand untuk membuat array random dengan ukuran yang telah kita tetapkan

In [24]:
a = np.floor(np.random.rand(2,2)*10)
a

array([[2., 2.],
       [3., 7.]])

#### Multitype Array
Memungkinkan kita membuat array dengan tipe yang telah kita tetapkan, semisal kita punya array yang isinya campuran seperti character dan numerical, jika tidak menggunakan multitipe dan dtype seperti dibawah ini maka hasil arraynya akan menjadi string semua.
> Dtypes documentation https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [20]:
dtipe = [('nama','S255'),('tinggi',int)]
data = [
    ('ucup',150),
    ('otong',160),
    ('mario',180)
]

e = np.array(data, dtype = dtipe)

print(e)
print(f"Member pertama doang = {e[0]}")
print(f"Tinggi doang {e["tinggi"]}")

[(b'ucup', 150) (b'otong', 160) (b'mario', 180)]
Member pertama doang = (b'ucup', 150)
Tinggi doang [150 160 180]


<hr></hr>

## **Arithmetic Operation (Element Wise)**
### Penjumlahan/Pengurangan (biasa)
As you can see down below, if we sum two list the result will be the combination of both list. However, if we sum up two numpy array the result will be the sum of each value. 

>Jika jumlah anggota array a dan array b tidak sama maka tidak bisa dijumlah. Hal ini berbahaya karena array numpy bersifat elementwise

In [42]:
import numpy as np

a = [1,2,3,4,5]
b = [6,7,8,9,10]

anp = np.array(a)
bnp = np.array(b)

hasillist = a+b
print(hasillist)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [43]:
hasilarray = anp + bnp
print(hasilarray)

[ 7  9 11 13 15]


### Perkalian/Pembagian (biasa)
Kita tidak bisa melakukan perkalian list dengan list, hal ini akan menghasilkan error. namun berbeda dengan array yang akan mengalikan masing masing valuenya, artinya value pertama x value pertama, value kedua x value kedua

In [51]:
hasillist = a * b
print(hasillist)

TypeError: can't multiply sequence by non-int of type 'list'

In [48]:
kali = anp * bnp
bagi = anp / bnp
print(kali)
print(bagi)

[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## **Martix Operation**
### Perkalian Martix (Dot Product)
Hasilnya akan berupa skalar quantity

$dot = a.b$

$dot = |a|~.~|b|~.~cos0$



In [2]:
import numpy as np
a2d = np.array(([1,2],
                [3,4]))
b2d = np.ones([2,2])

# perkalian matrix (bukan elementwise)
c = np.dot(a2d,b2d)
c2 = a2d.dot(b2d) # cara kedua menggunakan objek yang lainnya

print(c)
print(c2)


[[3. 3.]
 [7. 7.]]
[[3. 3.]
 [7. 7.]]


### Perkalian Martix (Cross Product)
A cross B dan B cross A akan berbeda hasilnya, berbeda dengan dot yang hasilnya akan sama. Hasilnya akan berupa vector quantity.

$a~x~b = ||a||~.~||b||~.~sin0~.~c~(arahnya)$

In [9]:
a = np.array([1,2,0])
b = np.array([2,1,0])

print(np.cross(a,b))
print(np.cross(b,a))

[ 0  0 -3]
[0 0 3]


<hr></hr>

## **Operation**
### Indexing

In [2]:
a = np.array([(2,2),(3,7)])
print(f"Nilai pertama adalah = {a[0][0]}") # bisa juga a[0] untuk mengeluarkan satu barisnya
print(f"Nilai maximum dari a = ", a.max())
print(f"Posisi maximum dari a = ", a.argmax())
print(f"Posisi maximum dari a = ", a.argmin())

Nilai pertama adalah = 2
Nilai maximum dari a =  7
Posisi maximum dari a =  3
Posisi maximum dari a =  0


### Shape

In [40]:
a.shape

(2, 2)

In [1]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7,8,9])

print("elemen pertama = ", a[0])
print("elemen ketujuh = ", a[6])
print("elemen terakhir = ", a[-1])

elemen pertama =  0
elemen ketujuh =  6
elemen terakhir =  9


### Slicing

In [68]:
print("elemen dari 1-6", a[0:6])
print("elemen dari 4 sampai akhir", a[3:])

elemen dari 1-6 [0 1 2 3 4 5]
elemen dari 4 sampai akhir [3 4 5 6 7 8 9]


### Iteration

In [ ]:
for i in a:
    print("value = ",i)

### Sorting
Ini akan mengurutkan per baris. Jadi tidak ada hubungan antar baris dalam sorting

In [46]:
import numpy as np

a = np.floor(np.random.rand(2,2)*10)
# berbeda dengan randn yang valuenya nilai acak yang terdistribusi secara normal (dengan rata-rata 0 dan varians 1)
print(a)
np.sort(a) # cara lain -> a.sort()
print(a)

[[5. 6.]
 [8. 0.]]
[[5. 6.]
 [8. 0.]]


In [45]:
print(np.argsort(a)) # ini menghasilkan posisi dari si a sebelum diurutkan
# cara ngitungnya dari baris pertama baru ke baris kedua [[1 2][3 4]]

[[0 1]
 [0 1]]


In [54]:
dtipe = [('nama','S10'),('tinggi',int)]
data = [
    ('ucup',170),
    ('otong',180),
    ('mario',190)
]

a = np.array(data, dtype=dtipe)
print(np.sort(a, order='tinggi'))

[(b'ucup', 170) (b'otong', 180) (b'mario', 190)]


Dibawah ini akan menghasilkan None karena fungsi sort sendiri tidak mengembalikan nilai, akan tetapi jika kita melakukan a.sort(), array a itu sendiri **akan diurutkan**. 

Berbeda dengan np.sort yang akan mengembalikan return array, `tanpa mengubah array asli`.

In [55]:
print(a.sort(order='tinggi')) 
print(a.sort(order='nama'))

None
None


### Transpose Matrix

In [16]:
print(a2d.transpose())
print(a2d.T) # cara kedua lebih singkat lagi

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


### Invers
Invers adalah kebalikan dari suatu matrix, untuk membuktikan bahwa matrix adalah invers yaitu jika A.A^-1 = I atau matrix Identitas
> Tapi tidak semua matrix memiliki invers

In [15]:
a = np.array([(1,-1),(1,1)])
a_inv = np.linalg.inv(a)
print(a_inv)
# ini pembuktiannya v
print(a.dot(a_inv))

[[ 0.5  0.5]
 [-0.5  0.5]]
[[1. 0.]
 [0. 1.]]


### Determinan

In [16]:
det_a = np.linalg.det(a)
print(det_a)

2.0


### Flatten Array, vector baris
Dijejerin biar jadi satu baris semua

In [18]:
print(a2d.ravel())
print(np.ravel(a2d))

[1 2 3 4]
[1 2 3 4]


### Reshape
Mengubah urutannya, sama seperti flatten array tapi dipotong sesuai yang kita tentukan

In [30]:
print(a2d.reshape(4,1))
print(a2d.shape)
print(a2d) #ini masih bentuk semula ga permanen

[[1]
 [2]
 [3]
 [4]]
(2, 2)
[[1 2]
 [3 4]]


### Resize
Berbeda dengan yang lainnya, resize akan merubah nilainya permanen ke variabelnya, jika berbeda dengan size aslinya resize akan menyesuaikan just like below

In [31]:
print(a2d) # padahal a2d kea gini
a2d.resize(3,2)
print(a2d) # berubah jadi gini

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [0 0]]


### Stacking
We can stack one matrix on the top or on the side of each other. with `hstack` and `vstack`

>Be careful with size of the matrix, if the size is diffrent it might cause an error for some stack

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.hstack([a,b]) # menumpuk secara horizontal
d = np.vstack([a,b])

c,d

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

### Persamaan Linear
Kita dapat menggunakan np.linealg.solve(a,y). dimana a adalah matrix yang akan dikali dengan sesuatu dan y adalah hasil dari perkalian a dengan sesuatu itu.

In [4]:
a = np.array([(2,3),(1,2)])
y = np.array([23,14])

ainv = np.linalg.inv(a)
x1 = ainv.dot(y)
print(x1)

# ini sama dengan v
x2 = np.linalg.solve(a,y)
print(x2)

[4. 5.]
[4. 5.]
